apiVersion: apps/v1
kind: Deployment
metadata:
  name: node1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node1
  template:
    metadata:
      labels:
        app: node1
    spec:
      containers:
        - name: nodeserver1
          image: manasvegi/nodeserver
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeserver1
  namespace: default
spec:
  type: NodePort
  selector:
    app: node1
  ports:
  - port: 3000
    targetPort: 3000